export const appRoutes = {
    home: '/',
    admin: '/admin',
    adminCollections: '/admin/collections',
    signUp: '/signUp',
    signIn: '/signIn',
    products: '/products',
    showroom: '/showroom',
    aboutUs: '/aboutUs',
    contact: '/contact',
    findRetail: '/find-retail',
    productDetails: '/product-details',
    cart: '/cart',
    comment: '/comment',
    errorPage: '*',
}